
version: 2

models:
  - name: bronze_cmic__employees
    description: "CMiC employee staging model"
##    columns:
##      - name: id
##        description: "The primary key for this table"
##        data_tests:
##          - unique
##         - not_null

##  - name: my_second_dbt_model
##    description: "A starter dbt model"
##    columns:
##      - name: id
##        description: "The primary key for this table"
##        data_tests:
##          - unique
##          - not_null
